export enum ENV {
  API_URL = "NEXT_PUBLIC_API_URL",
  KEY_PUSHER = "NEXT_PUBLIC_KEY_PUSHER",
  CLUSTER_PUSHER = "NEXT_PUBLIC_CLUSTER_PUSHER",
  CLOUDINARY_NAME = "CLOUDINARY_NAME",
  CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY",
  CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET",
}
